Debugging

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -23,11 +23,6 @@ jobs:
       matrix:
         executorId: [ 0, 1 ]
     steps:
-      - uses: azure/setup-helm@v4.2.0
-        id: helm
-        with:
-          version: 'latest'
-
       - name: Start a local k8s cluster
         uses: jupyterhub/action-k3s-helm@v4
         with:
@@ -89,7 +84,7 @@ jobs:
         run: kubectl get nodes
 
       - name: kubectl -n explorer get events
-        run: kubectl -n explorer get events
+        run: kubectl -n explorer get events --sort-by='.lastTimestamp'
 
       - name: kubectl -n explorer get all
         run: kubectl -n explorer get all
@@ -97,6 +92,7 @@ jobs:
       - name: Wait for weaviate startup
         run: |
           kubectl -n explorer wait --for=condition=Ready --timeout=60s pod/weaviate-0
+          kubectl -n explorer wait --for=jsonpath='{.status.loadBalancer.ingress}' --timeout=60s service/weaviate || echo "fail through"
 
       - name: Set up Python
         uses: actions/setup-python@v4
@@ -120,6 +116,7 @@ jobs:
           kubectl -n explorer wait --for=jsonpath='{.status.loadBalancer.ingress}' --timeout=120s service/explorer || echo "fail through"
           kubectl -n explorer get events --sort-by='.lastTimestamp'
           kubectl -n explorer describe service explorer
+          kubectl -n explorer describe service weaviate
 
       - name: kubectl -n explorer logs service/explorer
         run: kubectl -n explorer logs service/explorer
