Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -91,7 +91,9 @@ jobs:
       - name: Wait for app startup
         run: |
           kubectl -n explorer wait --for=condition=available --timeout=120s deployment/explorer
-          kubectl -n explorer wait --for=jsonpath='{.status.loadBalancer.ingress}' --timeout=300s service/explorer || echo "fail through"
+          kubectl -n explorer wait --for=jsonpath='{.status.loadBalancer.ingress}' --timeout=120s service/explorer || echo "fail through"
+          kubectl -n explorer get events --sort-by='.lastTimestamp'
+          kubectl -n explorer describe service explorer
           
       - name: kubectl -n explorer logs service/explorer
         run: kubectl -n explorer logs service/explorer
